name: 'ncc action'
description: 'use sidey79/ncc to compile and push your github action dist! 🚀'
author: 'Sidey79'
inputs:
  src: 
    description: 'source code dir/file to compile'
    required: true
  ncc_args:
    description: 'comma seperated args for ncc'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.cjs'
branding:
  icon: 'box'  
  color: 'green'
